#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""把 KaTeX 打成「模板可内嵌」的形态。
================================================================
为什么不用 CDN / 不用相对路径引字体：

  WebView 里模板是 `loadHtmlString(html)` 灌进去的 —— 页面没有 baseUrl，
  `url(fonts/x.woff2)` 这种相对路径**一定** 404。三条路：

    ① CDN            → 自习室 / 考场没网就白板
    ② loadHtmlString(baseUrl: file://…/templates/…)  → 改壳、还要保证字体
                        被 seedPublicTemplates 铺到公共目录、还要处理
                        私有兜底目录（没授权时 baseUrl 是另一条路径）
    ③ 字体 base64 内嵌 → 一个字符串，进 WebView 就是成品，不依赖任何路径

  选 ③。KaTeX 的 woff2 全集只有 ~296 KB，base64 后 ~395 KB ——
  比一张手机截图大不了多少，换掉整个「路径 / 授权 / 离线」问题，
  这笔账很划算。

  同时把 css 里 woff / ttf 两条回退 `url()` 删掉：Android 4.4 以上
  的 WebView 全支持 woff2 子集，留着只是白白让 CSS 大一倍。

产物（写进模板目录的 vendor/ 下）：
    katex.min.js         KaTeX 内核（~272 KB）
    auto-render.min.js   自动扫描 DOM 把 $…$ / $$…$$ 渲染掉（~10 KB）
    katex.css            字体已 data-uri 化的样式表（~400 KB）

用法：
    python3 tools/vendor_katex.py            # 用缓存，没有就下
    python3 tools/vendor_katex.py --refetch  # 强制重下

来源：https://registry.npmmirror.com/katex/-/katex-0.16.11.tgz
"""

import base64
import os
import re
import subprocess
import sys
import tarfile
import urllib.request

KATEX_VERSION = "0.16.11"
TGZ_URL = f"https://registry.npmmirror.com/katex/-/katex-{KATEX_VERSION}.tgz"

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
CACHE = "/workspace/.cache/katex"
TGZ = os.path.join(CACHE, f"katex-{KATEX_VERSION}.tgz")

# 两个模板目录都要铺：仓库根 templates/ 是参考副本，
# app/assets/templates/ 是打进 APK 的那份。
TARGETS = [
    os.path.join(ROOT, "templates", "plaincard_v1", "vendor"),
    os.path.join(ROOT, "app", "assets", "templates", "plaincard_v1", "vendor"),
]


def fetch(refetch=False):
    os.makedirs(CACHE, exist_ok=True)
    if refetch or not os.path.exists(TGZ):
        print(f"下载 {TGZ_URL}")
        urllib.request.urlretrieve(TGZ_URL, TGZ)
    print(f"用 {TGZ} ({os.path.getsize(TGZ)//1024} KB)")


def extract():
    ex = os.path.join(CACHE, "x")
    if not os.path.isdir(os.path.join(ex, "package", "dist")):
        os.makedirs(ex, exist_ok=True)
        with tarfile.open(TGZ) as t:
            t.extractall(ex)
    return os.path.join(ex, "package", "dist")


# KaTeX 的 @font-face 长这样（min 版一行一个）：
#   src:url(fonts/KaTeX_AMS-Regular.woff2) format("woff2"),
#       url(fonts/KaTeX_AMS-Regular.woff) format("woff"),
#       url(fonts/KaTeX_AMS-Regular.ttf) format("truetype");
# 只留 woff2，并且换成 data-uri。
SRC_RE = re.compile(
    r'src:url\(fonts/([A-Za-z0-9_\-]+)\.woff2\)\s*format\("woff2"\)'
    r'(?:\s*,\s*url\(fonts/[^)]+\)\s*format\("[^"]+"\))*'
)


def inline_fonts(css: str, fonts_dir: str) -> str:
    used = []

    def sub(m):
        name = m.group(1)
        path = os.path.join(fonts_dir, name + ".woff2")
        with open(path, "rb") as f:
            b64 = base64.b64encode(f.read()).decode("ascii")
        used.append(name)
        return f'src:url(data:font/woff2;base64,{b64}) format("woff2")'

    out = SRC_RE.sub(sub, css)
    # 漏网的相对 url()（如果有）宁可报出来，也不要静默留个 404
    left = re.findall(r"url\((?!#?data:)([^)]*)\)", out)
    if left:
        print("  ! 还有没内嵌的 url()：", left[:5], file=sys.stderr)
    print(f"  内嵌字体 {len(used)} 个：{', '.join(sorted(used)[:3])} …")
    return out


def main():
    fetch("--refetch" in sys.argv)
    dist = extract()

    with open(os.path.join(dist, "katex.min.css"), encoding="utf-8") as f:
        css = f.read()
    css = inline_fonts(css, os.path.join(dist, "fonts"))

    files = {
        "katex.min.js": open(os.path.join(dist, "katex.min.js"), encoding="utf-8").read(),
        "auto-render.min.js": open(
            os.path.join(dist, "contrib", "auto-render.min.js"), encoding="utf-8"
        ).read(),
        "katex.css": css,
        # 记一笔出处，省得以后有人对着 400KB 的一行 base64 发呆
        "VERSION.txt": (
            f"katex {KATEX_VERSION}\n"
            f"source {TGZ_URL}\n"
            "generated by tools/vendor_katex.py —— 不要手改，重跑脚本\n"
        ),
    }

    for target in TARGETS:
        os.makedirs(target, exist_ok=True)
        for name, content in files.items():
            with open(os.path.join(target, name), "w", encoding="utf-8") as f:
                f.write(content)
        total = sum(os.path.getsize(os.path.join(target, n)) for n in files)
        print(f"✓ {os.path.relpath(target, ROOT)}  ({total // 1024} KB)")


if __name__ == "__main__":
    main()
